import turtle
import random
t = turtle.Turtle()


turtle.Screen().screensize(600,500)
t.speed(10)
tamanho =random.randint(50,100)
tamanho2 =random.randint(20,50)
def tomate(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.color("black")
    t.fillcolor("red")
    t.begin_fill()
    t.circle(tamanho)
    t.end_fill()
    t.color("red")
    t.left(tamanho)
    t.forward(tamanho)
    t.color("green")
    t.pensize(5)
    t.forward(20)
    t.backward(20)
    t.left(45)
    t.forward(25)
    t.left(25)
    t.forward(25)
    t.backward(25)
    t.right(25)
    t.backward(25)
    t.left(35)
    t.forward(25)
    t.left(45)
    t.forward(25)
    t.backward(25)
    t.right(45)
    t.backward(25)
    t.right(115)
    t.forward(25)
    t.right(45)
    t.forward(25)
    t.backward(25)
    t.left(45)
    t.backward(25)
    t.right(45)
    t.forward(25)
    t.right(35)
    t.forward(25)
    t.color("black")
    t.pensize()
turtle.onscreenclick(tomate,1)
turtle.tracer(False)
turtle.done()